"""Write Marshal's shared words into the dashboard, so its "why?" slips say what the doctor says.

The sentences live in ``src/remembra/marshal/words.py``. The dashboard is
built from ``dashboard/`` alone (its Dockerfile copies nothing else), so it
gets them as a generated module, ``dashboard/src/lib/marshalWords.ts``, which
``lib/marshal.ts`` fills in at run time.

    python scripts/sync_marshal_words.py          # write
    python scripts/sync_marshal_words.py --check  # exit 1 if the dashboard's copy is stale
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "dashboard" / "src" / "lib" / "marshalWords.ts"
sys.path.insert(0, str(ROOT / "src"))

from remembra.marshal import words  # noqa: E402  (after the path above)


def render() -> str:
    def literal(value: object) -> str:
        return json.dumps(value, ensure_ascii=False)

    rules = []
    for rule, parts in words.SHARED_RULES.items():
        body = "".join(f"    {part}: {literal(text)},\n" for part, text in parts.items())
        rules.append(f"  {rule}: {{\n{body}  }},\n")
    return (
        "// Generated by scripts/sync_marshal_words.py from src/remembra/marshal/words.py. Do not edit:\n"
        "// change words.py and run `python scripts/sync_marshal_words.py`. The doctor\n"
        "// (remembra-relay doctor, remembra_doctor) says these same sentences for the same rule ids.\n"
        "\n"
        "/** Rules the doctor and the why? slip both reach: the call, one more sentence, the fix, the guide anchor. */\n"
        f"export const SHARED_RULES = {{\n{''.join(rules)}}} as const;\n"
        "\n"
        "export type SharedRule = keyof typeof SHARED_RULES;\n"
        "\n"
        "/** Verdicts only the slip reaches (the doctor can't see key use, and prints no finding when nothing is wrong). */\n"
        f"export const DASHBOARD_ONLY = {literal(list(words.DASHBOARD_ONLY))} as const;\n"
        "\n"
        "/** Said of every adapter that has never been run against its tool. */\n"
        f"export const UNVERIFIED = {literal(words.UNVERIFIED)};\n"
        "\n"
        "/** The Codex hooks connect writes, which Codex runs only once they are trusted. */\n"
        f"export const CODEX_TRUST_EVENTS = {literal(list(words.CODEX_TRUST_EVENTS))} as const;\n"
    )


def main(argv: list[str]) -> int:
    text = render()
    current = TARGET.read_text(encoding="utf-8") if TARGET.exists() else None
    if current == text:
        return 0
    if "--check" in argv:
        print(f"out of date, run python scripts/sync_marshal_words.py: {TARGET.relative_to(ROOT)}", file=sys.stderr)
        return 1
    TARGET.write_text(text, encoding="utf-8")
    print(f"updated {TARGET.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
