// Generated by scripts/sync_marshal_words.py from src/remembra/marshal/words.py. Do not edit:
// change words.py and run `python scripts/sync_marshal_words.py`. The doctor
// (remembra-relay doctor, remembra_doctor) says these same sentences for the same rule ids.

/** Rules the doctor and the why? slip both reach: the call, one more sentence, the fix, the guide anchor. */
export const SHARED_RULES = {
  KEY_MISSING: {
    what: "No API key {where}, so the hooks can't load or save handoffs.",
    doc: "#setup",
  },
  PICKS_UP_NEVER_CLOSES: {
    what: "{name} read {briefs} but never handed off: its close hasn't reached Remembra.",
    fix: "End one {name} session. If no handoff arrives, doctor names the failing close:",
    doc: "#doctor",
  },
  CODEX_TRUST_MISSING: {
    what: "Codex needs you to trust {hooks}: Codex Settings > Hooks > Trust.",
    detail: "Codex skips untrusted hooks without a message.",
    fix: "Open Codex Settings > Hooks, or run /hooks in the Codex CLI, and trust {events}.",
    doc: "#codex-trust",
  },
  NOTHING_WAITING: {
    what: "{name} hasn't ended a session with the hooks yet, and no handoff was waiting for it.",
    fix: "End one {name} session in a repository.",
    doc: "#doctor",
  },
  HOOKS_NOT_FIRING: {
    what: "The key works, but nothing from {name} has reached Remembra{since}.",
    doc: "#doctor",
  },
  STALE_CHECKPOINT: {
    what: "{name}'s last session stopped without a handoff.",
    detail: "Its newest entry is a checkpoint from {ago}, with no handoff after it.",
    fix: "In the repository it worked in, write the handoff now:",
    doc: "",
  },
} as const;

export type SharedRule = keyof typeof SHARED_RULES;

/** Verdicts only the slip reaches (the doctor can't see key use, and prints no finding when nothing is wrong). */
export const DASHBOARD_ONLY = ["KEY_NEVER_USED", "HANDED_OFF"] as const;

/** Said of every adapter that has never been run against its tool. */
export const UNVERIFIED = "{name}'s adapter is built from its hook docs and has never been run against the real tool.";

/** The Codex hooks connect writes, which Codex runs only once they are trusted. */
export const CODEX_TRUST_EVENTS = ["SessionStart", "UserPromptSubmit", "SessionEnd"] as const;
